faster-than-scrap/Sandbox/Wierzba/wierzba_sandbox.tscn
faster-than-scrap/code/ship/modules/module.gd
faster-than-scrap/code/ship/ship.gd
faster-than-scrap/prefabs/modules/module_base.tscn

I would leave implementation of explosion particles as another task

module base class

---

faster-than-scrap/code/game_state.gd
faster-than-scrap/code/mission_base.gd

Script containg only game state enums, and script containing only mission type enum. 
The second script can be used as a base for mission base sript

Added basic enums

---

faster-than-scrap/code/ship/ship.gd

part of #88 and required for #91

use energy ship interface

---

faster-than-scrap/art/audio/sounds/broń-laserowa 1.1.mp3.import
faster-than-scrap/art/audio/sounds/broń-laserowa 1.2.mp3.import
faster-than-scrap/code/mission_base.gd
faster-than-scrap/prefabs/mission_base.tscn

Mission base class

---

faster-than-scrap/code/effects/timed_gpu_particles_3d.gd

Timed particles

---

faster-than-scrap/Sandbox/Wierzba/flyable_ship/build_ship_flyable.tscn
faster-than-scrap/Sandbox/Wierzba/flyable_ship/fly_fly.tscn
faster-than-scrap/code/Player/player_ship.gd
faster-than-scrap/code/building_ship/ship_builder.gd
faster-than-scrap/code/ship/modules/module.gd
faster-than-scrap/code/ship/modules/weapons/weapon_module.gd
faster-than-scrap/code/weapons/base_weapon.gd
faster-than-scrap/code/weapons/constant_fire_weapon.gd
faster-than-scrap/code/weapons/spawner_weapon.gd
faster-than-scrap/prefabs/modules/joint.tscn
faster-than-scrap/prefabs/modules/module_base.tscn
faster-than-scrap/prefabs/modules/shield_module.tscn
faster-than-scrap/prefabs/modules/thruster.tscn
faster-than-scrap/prefabs/ships/flyable_ship.tscn
faster-than-scrap/project.godot

solves #199 
Created thruster prefab which implements weapon module.
Created two test scenes.
First one is for flying the ship, second one fer checking if builder work appropriately with new joints. To test it, you should detach and attach all modules from the cockpit, then attach everything (inlcluding thruster), and then press W. Pressing W before attaching will result in error.

Flyable ship

---

faster-than-scrap/Sandbox/Pisarski/weapon_demo.tscn
faster-than-scrap/code/ship/projectiles/beam.gd
faster-than-scrap/code/ship/projectiles/projectile.gd
faster-than-scrap/code/weapons/base_weapon.gd
faster-than-scrap/code/weapons/constant_fire_weapon.gd
faster-than-scrap/code/weapons/spawner_weapon.gd
faster-than-scrap/prefabs/modules/weapons/beam_weapon_module.tscn
faster-than-scrap/prefabs/modules/weapons/laser_weapon_module.tscn
faster-than-scrap/prefabs/projectiles/test_beam.tscn
faster-than-scrap/prefabs/projectiles/test_projectile.tscn

Resolves: #154, #87 (laser weapon) and #137, #124 (beam weapon)
Modules can be tested in sandbox scene weapon_demo.tscn (keys Q and E)

Projectiles and beams

---

faster-than-scrap/code/ship/modules/ghost.gd
faster-than-scrap/code/ship/modules/module.gd

fix ship builder. Modules was not creating ghosts as supposed to. Additionaly prevent colliding ghost with original module

Fix ship builder

---

faster-than-scrap/code/building_ship/ship_builder.gd
faster-than-scrap/code/ship/modules/module.gd
faster-than-scrap/prefabs/environment/space_environment.tscn
faster-than-scrap/prefabs/modules/cockpit.tscn
faster-than-scrap/prefabs/modules/frame1.tscn
faster-than-scrap/prefabs/modules/frame2.tscn
faster-than-scrap/prefabs/modules/module_base.tscn

prevent seting some keys and disable seting keys on some modules

---

faster-than-scrap/code/missions/a/mission_escape.gd
faster-than-scrap/code/vfx/leave_animation.gd
faster-than-scrap/code/vfx/portal_object.gd
faster-than-scrap/code/vfx/portal_object.gd.uid
faster-than-scrap/prefabs/environment/portal.tscn
faster-than-scrap/prefabs/vfx/leave_animation.tscn

Added VFX for portal object.
Portal leave animation now scales time properly

Portal object vfx added

---

faster-than-scrap/code/building_ship/ship_builder.gd

Orange build outline for unattached modules in ship builder

---

faster-than-scrap/project.godot

remove p from pause

---

faster-than-scrap/code/player/hud.gd

change zoom

---

faster-than-scrap/prefabs/modules/functional_components/direction_arrow.tscn
faster-than-scrap/prefabs/modules/thruster.tscn
faster-than-scrap/prefabs/modules/weapons/beam_module.tscn
faster-than-scrap/prefabs/modules/weapons/laser_module.tscn
faster-than-scrap/prefabs/modules/weapons/missile_module.tscn

#465
add direction arrow, that point module direction, to some modules

Display module direction #465

---

faster-than-scrap/project.godot

Enabled MSAA 4x antialiasing

---

faster-than-scrap/art/model_prefabs/ship/modules/bumper_model_pf.tscn
faster-than-scrap/art/model_prefabs/ship/modules/bumper_wide_model_pf.tscn
faster-than-scrap/code/singletons/modules_list.gd
faster-than-scrap/prefabs/modules/bumper.tscn
faster-than-scrap/prefabs/modules/bumper_wide.tscn
faster-than-scrap/prefabs/modules/thruster.tscn

Bumper modules

---

faster-than-scrap/code/map_select/map_manager.gd
faster-than-scrap/code/map_select/map_selector.gd
faster-than-scrap/code/missions/a/mission_kill_enemies.gd
faster-than-scrap/code/missions/a/mission_kill_enemies.gd.uid
faster-than-scrap/code/missions/info/mission_info.gd
faster-than-scrap/code/scene_loader.gd
faster-than-scrap/prefabs/map_select/full_maps/map1.tscn
faster-than-scrap/prefabs/map_select/nodes/templates/missions/mission_kill_enemies.tscn
faster-than-scrap/prefabs/ui/cutscenes/tutorials/missions/kill_enemies_tutorial.tscn
faster-than-scrap/scenes/levels/final/easy/shotgunners_kill_enemies.tscn
faster-than-scrap/scenes/map_selector.tscn

- Added mission to kill all enemies
- Changed labels in mission selector to RichTextLabels to support BBCode text effects
- Fixed bug with GameManager forgetting clearing it's `ships` array when entering/exiting a shop
- this also fixes the bug with missiles not tracking enemies after exiting the shop
- Added tutorial

Kill all enemies mission

---

faster-than-scrap/art/materials/bosses/vortex_boss/lightnings.tres
faster-than-scrap/art/shaders/graphs/lightnings.tres
faster-than-scrap/art/shaders/poison_cloud.tres
faster-than-scrap/prefabs/projectiles/boss_projectiles/vortex_cloud.tscn

Created vortex boss cloud - the missing prefab. Now it's a sphere (colliders changed accordingly)
Created by using new shader, and adding the lightning of different color. 
You can test in my sandbox boss_arena scene

Vortex boss cloud

---

faster-than-scrap/code/building_ship/ship_builder.gd
faster-than-scrap/scenes/build_ship.tscn
faster-than-scrap/scenes/tutorials/build_ship_tutorial.tscn

cancel selecting key

---

faster-than-scrap/prefabs/npc/bosses/vortex/vortex_boss.tscn
faster-than-scrap/prefabs/npc/bosses/vortex/vortex_boss_tentacle.tscn
faster-than-scrap/prefabs/projectiles/boss_projectiles/vortex_spike.tscn

Weaker vortex spike. It doesn't kill instantly (but deals quite lot damage), but also everything can pass through it

Vortex spike weaker

---

faster-than-scrap/scenes/credits.tscn

Added Vbox for containing multiple labels. Previously the one font size wasn't enough, so i splitted the text into 3 labels, co text is smaller when mentioning the asset.
Modified animation, so it changes the vbox instead of label
To test just play credits.tscn

Fix credits

---

faster-than-scrap/art/materials/scrap_shop/base/scrap_shop_shiny_material_3d.tres
faster-than-scrap/prefabs/environment/cultists_station_pf.tscn

Cultists? In my scrap shop?
It's more likely than you think.

Low budget cultist station

---

faster-than-scrap/code/building_ship/shop.gd
faster-than-scrap/scenes/build_ship.tscn

Fixed shop not properly calculating inventory size. Added exports for flexibility. Previously it behaved weirdly.
Now inventory iteam are positioned correctly

Include inventory size

---

faster-than-scrap/code/player/hud.gd
faster-than-scrap/code/singletons/settings_manager.gd
faster-than-scrap/project.godot

Adds camera panning functionality. Press the middle mouse button to pan the camera.

Camera panning

---

faster-than-scrap/scenes/tutorials/basic_movement_tutorial.tscn

Added transparency and changed color to orange to the boundary in the movement tutorial scene

Tutorial boundary - less defaulty look

---

faster-than-scrap/code/map_select/nodes/boss_node.gd
faster-than-scrap/prefabs/map_select/nodes/templates/boss_node.tscn
faster-than-scrap/prefabs/map_select/nodes/templates/missions/mission_defend.tscn
faster-than-scrap/prefabs/map_select/nodes/templates/missions/mission_escape.tscn
faster-than-scrap/prefabs/map_select/nodes/templates/missions/mission_fuel.tscn
faster-than-scrap/prefabs/map_select/nodes/templates/missions/mission_kill_enemies.tscn

Decrease map icons saturation

---

faster-than-scrap/prefabs/ui/cutscenes/build_tutorial_cutscene.tscn

Add new slide to build tutorial

---

faster-than-scrap/code/building_ship/shop.gd
faster-than-scrap/scenes/build_ship.tscn

Fixes tutorial shops still using the old repair particles (base_projectile_hit_particles)

Change default repair particles
